server:
  port: 8080


spring:
  #  数据库连接配置
  datasource:
    url: jdbc:mysql://192.168.3.149:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&serverTimezone=GMT%2B8
    username: root
    password: asdASD123.
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  redis:
    host: 192.168.3.127
    database: 0
    port: 6379
    timeout: 1000ms # 连接超时时间（毫秒）

#minio配置
#配置访问的地址
#用户名，密码
minio:
  endpoint: http://192.168.3.127:9000
  accessKey: admin
  secretKey: admin123

#mybatis 配置
mybatis:
  type-aliases-package: com.xdt.dataset_server.entity
  mapper-locations: classpath:mappers/*Mapper.xml
  #  驼峰命名转换
  configuration:
    map-underscore-to-camel-case: true
debug: true

#.yml
logging:
  file:
    name: /logs/data_server